include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
# https://github.com/rrousselGit/freezed/issues/488
# Fix issue: warning: The annotation 'JsonKey' can only be used on fields or getters
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore